# Generated by Django 3.2.15 on 2022-09-08 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plantId', models.AutoField(primary_key=True, serialize=False)),
                ('plantName', models.CharField(max_length=50)),
                ('disabledIconUrl', models.CharField(max_length=200)),
                ('activeIconUrl', models.CharField(max_length=200)),
                ('detailPictureUrl', models.CharField(max_length=500)),
                ('plantDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('collectId', models.AutoField(primary_key=True, serialize=False)),
                ('collectPictureUrl', models.CharField(max_length=200)),
                ('userId', models.IntegerField()),
                ('collectDate', models.DateField(auto_now_add=True)),
                ('collectContent', models.TextField()),
                ('plantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='plantbook.plant')),
            ],
        ),
    ]
