# Generated by Django 3.2.15 on 2022-09-22 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plantId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('plantName', models.CharField(max_length=50)),
                ('disabledIconUrl', models.CharField(max_length=500)),
                ('activeIconUrl', models.CharField(max_length=500)),
                ('detailPictureUrl', models.CharField(max_length=500)),
                ('plantDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('collectId', models.AutoField(primary_key=True, serialize=False)),
                ('collectPictureUrl', models.CharField(max_length=500)),
                ('collectDate', models.DateField(auto_now_add=True)),
                ('collectContent', models.TextField()),
                ('collectPlace', models.CharField(max_length=50)),
                ('plantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='plantbook.plant')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
