# Generated by Django 3.2.15 on 2022-09-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
