# Generated by Django 3.2.15 on 2022-09-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='areaCode',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collect',
            name='sigunguCode',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
