# Generated by Django 3.2.15 on 2022-09-26 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plantbook', '0002_auto_20220924_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='activeIconUrl',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='disabledIconUrl',
        ),
        migrations.AddField(
            model_name='collect',
            name='collectTitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='plantId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
