# Generated by Django 3.2.15 on 2022-09-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantbook', '0002_plant_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='classification',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='season',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
