# Generated by Django 3.2.15 on 2022-09-28 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('titleId', models.AutoField(primary_key=True, serialize=False)),
                ('titleName', models.CharField(max_length=50)),
                ('titleDescription', models.CharField(max_length=200)),
                ('titlePictureUrl', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Obtained',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.title')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obtained', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
