# Generated by Django 3.2.15 on 2022-09-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('userName', models.CharField(max_length=50)),
                ('userEmail', models.CharField(max_length=255)),
            ],
        ),
    ]
