# Generated by Django 3.2.15 on 2022-09-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220929_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
