# Generated by Django 3.2.15 on 2022-09-26 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='titleId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='titles.title'),
        ),
    ]
