# Generated by Django 3.2.15 on 2022-09-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
